### ISSUE TITLE
Semantic versioning recommends 0.1.0 as initial version

### ISSUE THREAD

**Issue by piratecarrot** [Mobject-Dev-Team/mobject-converters#3]
I am not sure if you are using the semantic versioning system, but if you are, the initial version number is recommended to be 0.1.0.
https://semver.org/

This is set correctly in the PLC project, however there is a tag with the version number v0.0.0-alpha.

> **How should I deal with revisions in the 0.y.z initial development phase?**
>The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

**Comment by benhar-dev** [comment]
Thank you @piratecarrot, I've now created mobject-coding-convention which will allow us to tie down any non-standard naming / numbering.  I've added the following section based on this.  Also, to cut down on work during alpha, I'll be following a few peoples style of adding the .library file to the project root rather than adding release / tags for it.  We will then reintroduce it once we have an automated build chain.  

https://mobject-dev-team.github.io/mobject-coding-convention/#/?id=library-version-numbering
